#!/bin/bash

export PATH=/usr/local/node/bin:$PATH


br=$1


fe=.
output=../b-fe-compiled
dest=b-fe-compiled/*

cd $fe

git pull


test -d $fe/node_modules || /usr/local/node/bin/npm install --registry=https://registry.npm.taobao.org

gulp deploy

test -d $output || mkdir -p $output
cp -r $dest $output



