#!/bin/bash

#br=$1

fe=.
output_public=../weishi-m-fe_compiled
output_public_old=../weishi-m-fe_compiled
startDate=$(date "+%s")
total=1

cd $fe

git pull

#node module有变化使用下面语句，保证都可以安装
#npm install --registry=https://registry.npm.taobao.org
test -d $fe/node_modules/fe-delta || npm install --registry=https://registry.npm.taobao.org

endDate1=$(date "+%s")
let timeRange=($endDate1-$startDate)
echo "npm install: ${timeRange}s"


#静态资源构建
echo $1
echo $2
chmod +x $fe/build.js
node $fe/build.js -s beta -d 1 -t $total -p $1 -l $2

#构建发生异常
if [[ $? == 1 ]]; then
    exit 1
fi

let endDate2=$(date "+%s")
let timeRange=($endDate2-$endDate1)
echo "fe build: ${timeRange}s"

#全量构建的时候执行下面语句
if [[ $total == 1 ]]; then
    rm -rf $output_public
fi
#拷贝打包文件和软链
test -L $output_public_old/view/v2 || ln -s $output_public/view/v2 $output_public_old/view/v2
test -d $output_public || mkdir -p $output_public
test -d $fe/output/view && cp -r $fe/output/view $output_public
test -d $fe/output/public && cp -r $fe/output/public $output_public

let endDate3=$(date "+%s")
let timeRange=($endDate3-$endDate2)
echo "copy file: ${timeRange}s"


#总耗时
let endDate=$(date "+%s")
let timeRange=($endDate-$startDate)
echo "Total: ${timeRange}s"