<!DOCTYPE html>
<html>
    <head>
        <meta name="google" value="notranslate" />
        <meta charset="utf-8" />
        <style>
            html,
            body {
                margin: 0;
                padding: 0;
                height: 100%;
            }
            object:focus {
                outline:none;
            }
        </style>


<?php

    $custom_path = '/src/video/';

    $flash_root = $custom_path;

    $userAgent = $this->request->getUserAgent();
    if (preg_match("/iPad|iPhone|Android|BlackBerry|Windows Phone|webOS/i", $userAgent)):
?>


        <script>
            var letvcloud_player_conf =  {
                "uu":"<?php echo $this->config->letv->user_unique;?>",
                "vu":"<?php echo $vu; ?>",
                "auto_play":1,
                "gpcflag":1,
                "width":676,
                "height":383
            };
        </script>
        <script src="http://yuntv.letv.com/bcloud.js"></script>
    </head>
    <body>

<?php else: ?>


        <link rel="stylesheet" href="<?php echo $this->url->getStatic($flash_root . '/history/history.css');?>?{edp-variable:{version}}" />
        <script src="<?php echo $this->url->getStatic($flash_root . '/history/history.js');?>?{edp-variable:{version}}"></script>

        <script src="<?php echo $this->url->getStatic($flash_root . '/swfobject.js');?>?{edp-variable:{version}}"></script>
        <script>
            function gomainpage()
            {
                window.parent.open('http://www.genshuixue.com', '_blank');
            }
            // For version detection, set to min. required Flash Player version, or 0 (or 0.0.0), for no version detection.
            var swfVersionStr = "11.1.0";
            // To use express install, set to playerProductInstall.swf, otherwise the empty string.
            var xiSwfUrlStr = "<?php echo $this->url->getStatic($flash_root . '/playerProductInstall.swf');?>?{edp-variable:{version}}";
            var flashvars = {
                "tailurl":"<?php echo $this->url->getStatic($flash_root . '/over.flv');?>?{edp-variable:{version}}",
                "logourl":"<?php echo $this->url->getStatic($flash_root . '/logo.flv');?>?{edp-variable:{version}}",
                "picStartUrl":"<?php echo $this->url->getStatic($flash_root . '/video_bg.png');?>?{edp-variable:{version}}",
                "uu":"<?php echo $this->config->letv->user_unique;?>",
                "vu1":"<?php echo $vu; ?>",
                "autoplay":0
                };
            var params = {};
            params.quality = "high";
            params.bgcolor = "#ffffff";
            params.allowscriptaccess = "sameDomain";
            params.allowfullscreen = "true";
            var attributes = {};
            attributes.id = "BJHLPlayer";
            attributes.name = "BJHLPlayer";
            attributes.align = "middle";
            swfobject.embedSWF(
                "<?php echo $this->url->getStatic($flash_root . '/BJHLPlayer.swf');?>?{edp-variable:{version}}", "flashContent",
                "100%", "100%",
                swfVersionStr, xiSwfUrlStr,
                flashvars, params, attributes);
            // JavaScript enabled so display the flashContent div in case it is not replaced with a swf object.
            swfobject.createCSS("#flashContent", "display:block;text-align:left;");
        </script>
    </head>
    <body>

        <div id="flashContent">

        </div>

<?php endif; ?>

    </body>
</html>
