#!/bin/bash

fe=$(pwd)
rd=$fe/../www
output=$fe/../www-fe-compiled

output_public=$output/public

cd $fe

git pull

if [[ $1 == "fast" ]]; then
    edp build -f
else
    edp build -f -s release
fi

mv $output $output.bak

mkdir -p $output_public
cp -r $fe/output/view $output
cp -r $fe/output/asset $output_public
cp -r $fe/cache-build/dep $output_public

cp $fe/tool/cert.js $output_public


rm -rf $output.bak